version: '3.4'
services:
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/mask
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: password